[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
LiteratePlotlyRepro = "53be1847-7b4c-45ee-9b47-020af0fdc354"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"

[compat]
Documenter = "1"
Literate = "2"
PlotlyJS = "0.18"
julia = "1.10"
